рефакторинг кода по результатам урока
aksilont/MyCar pull request #53
Opened 2022-05-14 21:13 UTC by alexlarin12

1. регистрация ячейки GarageCollectionViewCell без reuseidentifire
2. регистрация ячеек AutoCell и PopoverCell без reuseidentifire
3. обернул констрейнты элементов  в ячейках и контроллерах  в массивы
4. разгрузил от кода ViewDidLoad контроллеров и иниты ячеек
5. небольшой рефакторинг CheckMark
6. исправил баг с неправильным заполнением текстфилдов в AddViewController
7. мелочи: закруглил ячейку GarageCell, исправил орфографию  "case" в "enam"

2022-05-15 16:14 UTC, aksilont approved these changes

2022-05-15 16:14 UTC, aksilont commented on MyCar/App/Flows/Scenes/AddAuto/AddAutoViewController.swift
>      let carParametrsModel = CarParametrsModel()
Вот эти модели и сервис по-хорошему вывести во ViewModel, например, AddAutoViewModel и уже с этим работать

2022-05-15 16:14 UTC, aksilont commented on MyCar/App/Flows/Scenes/AddAuto/AddAutoViewController.swift
>              self.navigationController?.popToRootViewController(animated: true)
Вот здесь еще надо сделать просто popViewController вместо popToRootViewController

2022-05-16 00:42 UTC, pkslty commented on MyCar/App/Flows/Scenes/AddAuto/AddAutoViewController.swift
>              self.navigationController?.popToRootViewController(animated: true)
Согласен, это путь к перезапуску приложения после сохранения

2022-05-16 00:53 UTC, pkslty commented on MyCar/App/Flows/Scenes/AddAuto/AddAutoViewController.swift
> -        delegate?.appendAuto(carModel)
На мой взгляд заморочка с делегатом была лишняя. В гараже можно просто подгружать машины во viewwillappear

2022-05-16 01:04 UTC, pkslty requested changes
Критично:
Поправить возврат по кнопке сохранения
Общие замечания:
1. Поля надо бы проверять на корректность данных (год, например, пробег)
2. При сохранении первого авто ставить ему флаг активного (возможно это должно быть вообще не в этом контроллере)

2022-05-16 10:10 UTC, pkslty commented on MyCar/App/Flows/Scenes/Garage/GarageCollectionViewController.swift
> +            collectionView.reloadData()
Как минимум после if - else можно перенести carRepository.saveCar(carModel: cars[i]), чтоб не писать дважды. Но меня все это смущает. Я думаю в репозиторий надо написать метод апдейта модели и апдейтить только две сменившие флаг. Тем более что в дальнейшем захочется редактировать машину, не удалять же снова все по таакому случаю.

2022-05-16 10:12 UTC, pkslty approved these changes

2022-05-16 10:40 UTC, merged